#coding=utf-8

import requests
import json
import re
from resource.resource import *
from resource.logger import *



logger.info("治疗方案申请")
#治疗方案申请
data ={'nousercheck':1,'eventcode':'ApplyTreatmentPlan','funid':'sysevent','RequestDate':'20171205105516',
        'RequestId':'20171205105516165181220_HIS01_HIS01RQ000009','trancode':10,
       'data':json.dumps( {"TranCode": "10",
        "AdmissionDate": "2018-03-11",
        "AdmissionNumber": "0",
        "ApplyDiseaseInfo": [
            {
                "DiseasesCode": "600802",
                "DiseasesName": "2型糖尿病"
            }
        ],
        "Birthday": "1969-01-05",
        "DepartDate": "2017-12-11",
        "DepartmentCode": "38",
        "DepartmentName": "糖尿病科",
        "DiagnoseDiseaseInfo": [
            {
                "DiseasesCode": "E14.901",
                "DiseasesName": "糖尿病"
            },
            {
                "DiseasesCode": "E14.408+",
                "DiseasesName": "糖尿病性周围神经病"
            }
        ],
        "DistrictCode": "510181",
        "DoctorHISID": "85",
        "DoctorHISName": "胡孝荣",
        "Gender": "2",
        "InstituteID": "181220",
        "InstituteName": "糖尿病专科医院",
        "InsuranceType": "医保_001",
        "MainDiseaseDesc": "糖尿病",
        "MedicalType": "16",
        "PatientName": "杨群辉",
        "PhysicianDiagnosticAdvice": "",
        "ReferralTime": "2017-11-29 10:51:58",
        "SecurityCode": "016045308",
        "TreatmentPlanInfo": {
            "BeginDate": "2018-03-11",
            "EndDate": "2017-12-11",
            "TreatmentPlanBizNO": "21666",
            "TreatmentPlanItemInfo": [
                {
                    "AmountOfOnce": 50,
                    "AmountOfOnceUnit": "2",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "86902122000015",
                    "DirectoryItemName": "阿卡波糖胶囊(四川绿叶宝光药业股份有限公司)",
                    "HospitalItemCode": "2505",
                    "HospitalItemName": "阿卡波糖胶囊(50mg*30粒)",
                    "ItemSpec": "50mg*30粒",
                    "MinAmount": 50,
                    "MinAmountUnit": "2",
                    "Period": 1,
                    "TotalAmount": 273,
                    "TotalPrice": 431.6949,
                    "UnitPrice": 1.5813,
                    "UsageUnit": "9",
                    "Usage_Frequency": "3",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1.5,
                    "AmountOfOnceUnit": "1",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "86902665000275",
                    "DirectoryItemName": "十味玉泉胶囊(河北田顺华仁堂药业有限公司)",
                    "HospitalItemCode": "2179",
                    "HospitalItemName": "十味玉泉胶囊(0.5g*48粒)",
                    "ItemSpec": "0.5g*48粒",
                    "MinAmount": 0.5,
                    "MinAmountUnit": "1",
                    "Period": 1,
                    "TotalAmount": 819,
                    "TotalPrice": 822.0303,
                    "UnitPrice": 1.0037,
                    "UsageUnit": "9",
                    "Usage_Frequency": "3",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 2,
                    "AmountOfOnceUnit": "2",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "86902777003355",
                    "DirectoryItemName": "格列美脲分散片(石药集团中诺药业(石家庄)有限公司)",
                    "HospitalItemCode": "2532",
                    "HospitalItemName": "格列美脲分散片(2mg*12片)",
                    "ItemSpec": "2mg*12片",
                    "MinAmount": 2,
                    "MinAmountUnit": "2",
                    "Period": 1,
                    "TotalAmount": 91,
                    "TotalPrice": 179.3974,
                    "UnitPrice": 1.9714,
                    "UsageUnit": "8",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 120,
                    "AmountOfOnceUnit": "6",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "86902068001053",
                    "DirectoryItemName": "胰激肽原酶肠溶片(成都通德药业有限公司)",
                    "HospitalItemCode": "2225",
                    "HospitalItemName": "胰激肽原酶肠溶片(120u*40片)",
                    "ItemSpec": "120u*40片",
                    "MinAmount": 120,
                    "MinAmountUnit": "6",
                    "Period": 1,
                    "TotalAmount": 273,
                    "TotalPrice": 224.6244,
                    "UnitPrice": 0.8228,
                    "UsageUnit": "8",
                    "Usage_Frequency": "3",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250301001",
                    "DirectoryItemName": "血清总蛋白测定",
                    "HospitalItemCode": "1638",
                    "HospitalItemName": "血清总蛋白测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 0.8,
                    "UnitPrice": 0.8,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250301002",
                    "DirectoryItemName": "血清白蛋白测定",
                    "HospitalItemCode": "1640",
                    "HospitalItemName": "血清白蛋白测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 0.8,
                    "UnitPrice": 0.8,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "47",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250302001",
                    "DirectoryItemName": "葡萄糖测定",
                    "HospitalItemCode": "1642",
                    "HospitalItemName": "葡萄糖测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "47",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 32,
                    "UnitPrice": 3.2,
                    "UsageUnit": "44",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305001",
                    "DirectoryItemName": "血清总胆红素测定",
                    "HospitalItemCode": "1654",
                    "HospitalItemName": "血清总胆红素测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3.2,
                    "UnitPrice": 3.2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305002",
                    "DirectoryItemName": "血清直接胆红素测定",
                    "HospitalItemCode": "1656",
                    "HospitalItemName": "血清直接胆红素测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3.2,
                    "UnitPrice": 3.2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305003",
                    "DirectoryItemName": "血清间接胆红素测定",
                    "HospitalItemCode": "1658",
                    "HospitalItemName": "血清间接胆红素测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3.2,
                    "UnitPrice": 3.2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305007",
                    "DirectoryItemName": "血清丙氨酸氨基转移酶测定",
                    "HospitalItemCode": "1660",
                    "HospitalItemName": "血清丙氨基转移酶测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 4,
                    "UnitPrice": 4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250307001",
                    "DirectoryItemName": "尿素测定",
                    "HospitalItemCode": "1662",
                    "HospitalItemName": "尿素测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3,
                    "UnitPrice": 3,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250307002",
                    "DirectoryItemName": "肌酐测定",
                    "HospitalItemCode": "1664",
                    "HospitalItemName": "肌酐测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3,
                    "UnitPrice": 3,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102005",
                    "DirectoryItemName": "尿蛋白定性",
                    "HospitalItemCode": "1690",
                    "HospitalItemName": "尿蛋白定性",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 10,
                    "UnitPrice": 1,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102010",
                    "DirectoryItemName": "尿糖定性试验",
                    "HospitalItemCode": "1691",
                    "HospitalItemName": "尿糖定性试验",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 20,
                    "UnitPrice": 2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102013",
                    "DirectoryItemName": "尿三胆检查",
                    "HospitalItemCode": "1692",
                    "HospitalItemName": "尿三胆检查",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 8,
                    "UnitPrice": 0.8,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102003",
                    "DirectoryItemName": "尿比重测定",
                    "HospitalItemCode": "1898",
                    "HospitalItemName": "尿比重测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 10,
                    "UnitPrice": 1,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102012",
                    "DirectoryItemName": "尿酮体定性试验",
                    "HospitalItemCode": "1899",
                    "HospitalItemName": "尿酮体定性试验",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 20,
                    "UnitPrice": 2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102002",
                    "DirectoryItemName": "尿酸碱度测定",
                    "HospitalItemCode": "1900",
                    "HospitalItemName": "尿酸碱度测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 10,
                    "UnitPrice": 1,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305008",
                    "DirectoryItemName": "血清天门冬氨酸氨基转移酶测定",
                    "HospitalItemCode": "1902",
                    "HospitalItemName": "血清天门冬氨酸转移酶测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 4,
                    "UnitPrice": 4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305009",
                    "DirectoryItemName": "血清γ-谷氨酰基转移酶测定",
                    "HospitalItemCode": "1903",
                    "HospitalItemName": "血清r-谷氨酰基转移酶测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 4,
                    "UnitPrice": 4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250305011",
                    "DirectoryItemName": "血清碱性磷酸酶测定",
                    "HospitalItemCode": "1904",
                    "HospitalItemName": "血清碱性磷酸酶测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 2.4,
                    "UnitPrice": 2.4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250307005",
                    "DirectoryItemName": "血清尿酸测定",
                    "HospitalItemCode": "1905",
                    "HospitalItemName": "血清尿酸测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 4,
                    "UnitPrice": 4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "YYGYA100008",
                    "DirectoryItemName": "特殊采血管[国产]",
                    "HospitalItemCode": "1955",
                    "HospitalItemName": "特殊采血管",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 1.2,
                    "UnitPrice": 1.2,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "47",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL12040000201",
                    "DirectoryItemName": "静脉采血",
                    "HospitalItemCode": "2051",
                    "HospitalItemName": "静脉采血",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "47",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 3,
                    "UnitPrice": 3,
                    "UsageUnit": "44",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "47",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250102023",
                    "DirectoryItemName": "尿沉渣镜检",
                    "HospitalItemCode": "2709",
                    "HospitalItemName": "尿沉渣镜检",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "47",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 40,
                    "UnitPrice": 4,
                    "UsageUnit": "44",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "46",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "ZL250306005",
                    "DirectoryItemName": "乳酸脱氢酶测定",
                    "HospitalItemCode": "3034",
                    "HospitalItemName": "乳酸脱氢酶测定",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "46",
                    "Period": 91,
                    "TotalAmount": 1,
                    "TotalPrice": 4,
                    "UnitPrice": 4,
                    "UsageUnit": "43",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "14",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "YYZF000000",
                    "DirectoryItemName": "自费材料",
                    "HospitalItemCode": "4850",
                    "HospitalItemName": "一次性尿杯",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "14",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 6.9,
                    "UnitPrice": 0.69,
                    "UsageUnit": "11",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                },
                {
                    "AmountOfOnce": 1,
                    "AmountOfOnceUnit": "45",
                    "ChargeLevelCode": "",
                    "DirectoryItemCode": "YYG700054",
                    "DirectoryItemName": "血糖试纸[国产]",
                    "HospitalItemCode": "4862",
                    "HospitalItemName": "血糖试纸",
                    "ItemSpec": "",
                    "MinAmount": 1,
                    "MinAmountUnit": "45",
                    "Period": 9,
                    "TotalAmount": 10,
                    "TotalPrice": 40,
                    "UnitPrice": 4,
                    "UsageUnit": "7",
                    "Usage_Frequency": "1",
                    "UseDrugDays": 90
                }
            ],
            "TreatmentPlanSerialNO": "181220-21666"
        }
    })}


r = requests.post(test_url_z,data=data)
t=r.text


tt=t.replace('success',"\"success\"")
tt=tt.replace('true',"\"true\"")
tt=tt.replace('data',"\"data\"")
tt=tt.replace('message',"\"message\"")
re=eval(tt)

print(re['data']['ProcessInfo'])